executable = condor_Output_GOF_Data_Jobs.sh
arguments  = $(ProcId)
output     = condor_Output_GOF_Data_Jobs.$(ClusterId).$(ProcId).out
error      = condor_Output_GOF_Data_Jobs.$(ClusterId).$(ProcId).err

# Send the job to Held state on failure
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)

+JobFlavour = "workday"
queue 1